name: tbd-env
channels:
 - anaconda
 - conda-forge
 - pytorch
 - defaults
dependencies:
  - python=3.7
  - numpy
  - matplotlib
  - h5py
  - scipy
  - torchvision=0.4.1=py37_cu100
  - pytorch=1.3.0=py3.7_cuda10.0.130_cudnn7.6.3_0
  - scikit-image
  - pillow
