name: lest-env
channels:
 - conda-forge
 - pytorch
dependencies:
  - python=3.6
  - numpy
  - matplotlib
  - h5py
  - pathlib2
  - scipy
  - torchvision==0.6.1
  - pytorch==1.5.1
  - typing
  - opencv
  - scikit-learn
  - scikit-image
  - six
  - pillow
  - configobj
